
project_id = "hyoaegvyvmzpbvhtzbpv"

[functions]
[functions.oauth-login]
verify_jwt = false

[functions.oauth-callback]
verify_jwt = false

[functions.user-guilds]
verify_jwt = true

[functions.add-server]
verify_jwt = true

[functions.upsert-user-function]
verify_jwt = true

