
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eahmzxgmnyacbwahdanv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhaG16eGdtbnlhY2J3YWhkYW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODM0NzAsImV4cCI6MjA2MDE1OTQ3MH0.5a8Gq0GUQKVXT5tBq2y5QAw9mVg2K4qsgtsIa5nR2mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
