
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyoaegvyvmzpbvhtzbpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5b2FlZ3Z5dm16cGJ2aHR6YnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTM2MTIsImV4cCI6MjA2MDA2OTYxMn0.nIm9ylLxz9LAMyz8ysyiHUruLJF1ifxcXNAPy1_LrFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});
